version: '3.8'

services:
  react-app:
    image: restaurante-react-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true
